image: node:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm run coverage
  artifacts:
    paths:
      - coverage/lcov-report/
      
pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/lcov-report/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

publish:
  stage: deploy
  dependencies:
    - build
    - test
  script:
    - node node_modules/.bin/semantic-release-gitlab
  only:
    - master